# Generated by Django 4.2 on 2023-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Last_name', models.TextField(blank=True)),
                ('age', models.IntegerField()),
                ('profession', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
